apiVersion: v1
kind: Secret
metadata:
  name: product-secret
type: Opaque
data:
  MONGO_URI: bW9uZ29kYitzcnY6Ly9lY29tbWVyY2U6c0gzMndVWkpMa2lZNmFHUUBjbHVzdGVyMC5tdXVhOWl0Lm1vbmdvZGIubmV0L3Byb2R1Y3Q/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5JmFwcE5hbWU9Q2x1c3RlcjA=


  # mongodb://ecommerce:sH32wUZJLkiY6aGQ@cluster0.muua9it.mongodb.net/product?retryWrites=true&w=majority&appName=Cluster0