# secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: category-secret
type: Opaque
data:
  MONGO_URI: bW9uZ29kYitzcnY6Ly9lY29tbWVyY2U6c0gzMndVWkpMa2lZNmFHUUBjbHVzdGVyMC5tdXVhOWl0Lm1vbmdvZGIubmV0L2NhdGVnb3J5P3JldHJ5V3JpdGVzPXRydWUmdz1tYWpvcml0eSZhcHBOYW1lPUNsdXN0ZXIw



# mongodb://ecommerce:sH32wUZJLkiY6aGQ@cluster0.muua9it.mongodb.net/category?retryWrites=true&w=majority&appName=Cluster0

# apiVersion: v1
# kind: Secret
# metadata:
#   name: category-service-secrets
# type: Opaque
# data:
#   MONGO_URI: bW9uZ29kYjovL2Vjb21tZXJjZTpzSDMyd1VaSkxraVk2YUdRQGNsdXN0ZXIwLm11eWE5aXQubW9uZ29kYi5uZXQvY2F0ZWdvcnk/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5
#   # MONGO_URI: bW9uZ29kYitzcnY6Ly9lY29tbWVyY2U6c0gzMndVWkpMa2lZNmFHUUBjbHVzdGVyMC5tdXVhOWl0Lm1vbmdvZGIubmV0L2NhdGVnb3J5P3JldHJ5V3JpdGVzPXRydWUmdz1tYWpvcml0eSZhcHBOYW1lPUNsdXN0ZXIw

