apiVersion: v1
kind: Secret
metadata:
  name: user-secret
type: Opaque
data:
  JWT_SECRET: dXNlcmFuZGFkbWlu
  REFRESH_TOKEN_SECRET: dXNlcmFuZGFkbWlucmVmcmVzaHRva2Vu
  POSTGRES_URL: cG9zdGdyZXM6Ly9kZWZhdWx0OklFdzc1ckJicGFVTUBlcC1kcnktZHJlYW0tYTFuZTBoODMtcG9vbGVyLmFwLXNvdXRoZWFzdC0xLmF3cy5uZW9uLnRlY2g6NTQzMi92ZXJjZWxkYj9zc2xtb2RlPXJlcXVpcmU=